sudo: required
branches:
  only:
    - master
    - next
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker

language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

env:
  global:
  - ROUTERS=hb
  - ORG=mfdz
  # this is of course not the real feed URL but just a random public one so the build works
  - MFDZ_GTFS_URL=https://transitfeeds.com/p/b-rgerbus-leupoldsgr-n-landkreis-hof/1126/latest/download

script:
  - npm run test && ./travis-build.sh
