sudo: required
branches:
  only:
    - master
    - next
    - /201[7-9][0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker

language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

env:
  global:
  - ROUTERS=hb
  - ORG=mfdz

script:
  - npm run test && ./travis-build.sh
